# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.TextField(default='')),
                ('major', models.TextField(default='')),
                ('school', models.TextField(default='')),
                ('yearCompleted', models.TextField(default='')),
            ],
            options={
                'ordering': ('-yearCompleted',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobTitle', models.TextField(default='')),
                ('employer', models.TextField(default='')),
                ('startYear', models.TextField(default='')),
                ('endYear', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(default='')),
                ('middleInitial', models.TextField(default='')),
                ('lastName', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='michael.Person'),
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='michael.Person'),
        ),
    ]
